SUPABASE_URL="https://orzptlqiwcrzadcdbthf.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yenB0bHFpd2NyemFkY2RidGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NjA2NDksImV4cCI6MjA0OTEzNjY0OX0.WKx6t11mKjtGM9F9irZN2PcRh3RG9WomsjEMIYxL-6Q"
BAI_URL="https://raw.githubusercontent.com/kotaroburrito/mahjong/blob/master/images/bai.PNG"
FA_URL="https://raw.githubusercontent.com/kotaroburrito/mahjong/master/images/fa.PNG"
BAI_ZHONG="https://raw.githubusercontent.com/kotaroburrito/mahjong/master/images/bai.PNG"
